# Generated by Django 3.2.14 on 2022-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.TextField()),
                ('FOLIO', models.TextField()),
                ('OWNER', models.TextField()),
                ('ADDR_1', models.TextField()),
                ('ADDR_2', models.TextField()),
                ('CITY', models.TextField()),
                ('STATE', models.TextField()),
                ('ZIP', models.TextField()),
                ('NUMBER_OF_BEDS', models.TextField()),
                ('NUMBER_OF_BATHS', models.TextField()),
                ('SQUARE_FEET', models.TextField()),
                ('YEAR_BUILT', models.TextField()),
                ('NUMBER_OF_STORIES', models.TextField()),
                ('NUMBER_OF_UNITS', models.TextField()),
                ('ACREAGEACREAGE', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.TextField()),
                ('FOLIO', models.TextField()),
                ('SALE_AMOUNT', models.TextField()),
                ('SALE_DATE', models.TextField()),
                ('GRANTOR', models.TextField()),
                ('GRANTEE', models.TextField()),
                ('COUNTY', models.TextField()),
            ],
        ),
    ]
