# Generated by Django 3.2.14 on 2022-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelinfo',
            name='COUNTY',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
