# Generated by Django 3.2.14 on 2022-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_investors', '0002_parcelinfo_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.TextField()),
                ('FOLIO', models.TextField()),
                ('LATITUDE', models.TextField()),
                ('LONGITUDE', models.TextField()),
                ('COUNTY', models.TextField()),
            ],
        ),
    ]
