# Generated by Django 3.2.14 on 2022-09-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_investors', '0003_parcelcoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelcoordinates',
            name='LATITUDE',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name='parcelcoordinates',
            name='LONGITUDE',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
    ]
