# Generated by Django 3.2.14 on 2022-09-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_investors', '0004_auto_20220909_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.TextField()),
                ('PURCHASE_DATE', models.DateField()),
                ('SALE_DATE', models.DateField()),
                ('SALE_AMOUNT', models.DecimalField(decimal_places=2, max_digits=19)),
                ('PURCHASE_AMOUNT', models.DecimalField(decimal_places=2, max_digits=19)),
                ('GRANTOR', models.TextField()),
                ('GRANTEE', models.TextField()),
                ('PROFIT', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
