# Generated by Django 3.2.14 on 2022-09-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_investors', '0005_investorhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorhistory',
            name='GRANTEE',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='investorhistory',
            name='GRANTOR',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='investorhistory',
            name='PROFIT',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='investorhistory',
            name='PURCHASE_AMOUNT',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='investorhistory',
            name='PURCHASE_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investorhistory',
            name='SALE_AMOUNT',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='investorhistory',
            name='SALE_DATE',
            field=models.DateField(null=True),
        ),
    ]
